### ISSUE TITLE
Arch的QQ已经无法安装

### ISSUE THREAD

**Issue by Aloento** [wszqkzqk/deepin-wine-containers-for-ubuntu#2]
source=("$_mirror/pool/non-free/d/deepin.com.qq.office/deepin.com.qq.office_**2.0.0deepin4_**i386.deb"
MD5也不正确了，Skip后
mv: 无法获取'/home/wszqkzqk-deepin-wine-tim-arch/src/dpkgdir/usr/local/share/*' 的文件状态(stat): 没有那个文件或目录

**Comment by wszqkzqk** [comment]
添加archcn源，已推送至安装源里面
